// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFWutmKWWyZcP-Ih8HHOcSXKWDTh0nwB0',
    appId: '1:908856160324:web:f2cd4542f89684bf9f8c11',
    messagingSenderId: '908856160324',
    projectId: 'bechaalany-debt-app-e1bb0',
    authDomain: 'bechaalany-debt-app-e1bb0.firebaseapp.com',
    storageBucket: 'bechaalany-debt-app-e1bb0.firebasestorage.app',
    measurementId: 'G-VMWE4KDNBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJD7jdtZO-cHnDaUku7gHCvZZHp_3xXA4',
    appId: '1:908856160324:android:1a848127d23fd5c59f8c11',
    messagingSenderId: '908856160324',
    projectId: 'bechaalany-debt-app-e1bb0',
    storageBucket: 'bechaalany-debt-app-e1bb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc9aVixuplm5hJLI3YcKkoA9b41blf2EE',
    appId: '1:908856160324:ios:08460e3562c039349f8c11',
    messagingSenderId: '908856160324',
    projectId: 'bechaalany-debt-app-e1bb0',
    storageBucket: 'bechaalany-debt-app-e1bb0.firebasestorage.app',
    iosBundleId: 'com.bechaalany.debt.bechaalanyDebtApp',
  );
}
