// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTmvk5pfyn80jqSJCKKM8Oqkuoz05cZTA',
    appId: '1:908856160324:web:857794700f26f9569f8c11',
    messagingSenderId: '908856160324',
    projectId: 'bechaalany-debt-app-e1bb0',
    authDomain: 'bechaalany-debt-app-e1bb0.firebaseapp.com',
    storageBucket: 'bechaalany-debt-app-e1bb0.firebasestorage.app',
    measurementId: 'G-Q093R7HEY9',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc9aVixuplm5hJLI3YcKkoA9b41blf2EE',
    appId: '1:908856160324:ios:08460e3562c039349f8c11',
    messagingSenderId: '908856160324',
    projectId: 'bechaalany-debt-app-e1bb0',
    storageBucket: 'bechaalany-debt-app-e1bb0.firebasestorage.app',
    iosBundleId: 'com.bechaalany.debt.bechaalanyDebtApp',
  );
}
